// This file is required for Expo/React Native SQLite migrations
// Auto-generated by drizzle-kit - DO NOT EDIT MANUALLY

// Temporary empty migrations until drizzle-kit can detect schema
export default {
  journal: { version: '7', dialect: 'sqlite', entries: [] },
  migrations: {},
};
