version: 2
updates:
  # Enable version updates for npm (Yarn)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "mehotkhan"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "mehotkhan"
    labels:
      - "dependencies"
      - "client"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/worker"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "mehotkhan"
    labels:
      - "dependencies"
      - "worker"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    reviewers:
      - "mehotkhan"
    labels:
      - "ci/cd"
      - "automated"
    commit-message:
      prefix: "ci"

  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    directory: "/client/android"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "mehotkhan"
    labels:
      - "dependencies"
      - "android"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"

