# These are supported funding model platforms

github: [mehotkhan]
patreon: # Replace with your Patreon username
open_collective: # Replace with your Open Collective name
ko_fi: # Replace with your Ko-fi username
tidelift: # Replace with your Tidelift platform-name/package-name
community_bridge: # Replace with your Community Bridge project-name
liberapay: # Replace with your Liberapay username
issuehunt: # Replace with your IssueHunt username
otechie: # Replace with your Otechie username
custom: ['https://paypal.me/mehotkhan', 'https://buymeacoffee.com/mehotkhan']
