name = "safarnak-worker"
main = "worker/index.ts"
compatibility_date = "2025-10-11"
workers_dev = true

[observability]

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

# Development server configuration
[dev]
port = 8787
host = "0.0.0.0"

[[d1_databases]]
binding = "DB"
database_name = "my-d1-db"
database_id = "e4dd65e6-4417-4c6e-b1f8-5e96f3d22643"
migrations_dir = "database/migrations"

[durable_objects]
bindings = [
  { name = "SUBSCRIPTION_POOL", class_name = "SubscriptionPool" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SubscriptionPool"]

## ============================================================================
## KV Namespaces
## ============================================================================

[[kv_namespaces]]
binding = "KV"
id = "aaa95f080d984c5c854b08ff979a1643"
preview_id = "157b382a2e4440b7922383de844e79b1"

## ============================================================================
## R2 Buckets
## ============================================================================

[[r2_buckets]]
binding = "R2"                     # Access via env.R2
bucket_name = "safarnak-dev"       # Create via: wrangler r2 bucket create safarnak-dev

## ============================================================================
## Vectorize Index (AI Embeddings)
## ============================================================================

[[vectorize]]
binding = "VECTORIZE"              # Access via env.VECTORIZE
index_name = "safarnak-embeddings" # Create via: wrangler vectorize index create safarnak-embeddings --dimension 768


## ============================================================================
## Build Rules - Load .graphql files as text for schema import
## ============================================================================

[[rules]]
type = "Text"
globs = ["**/*.graphql"]
fallthrough = false


