name = "safarnak-worker"
main = "worker/index.ts"
compatibility_date = "2025-10-20"
workers_dev = true

# Development server configuration
[dev]
port = 8787
host = "0.0.0.0"

[[d1_databases]]
binding = "DB"
database_name = "my-d1-db"
database_id = "e4dd65e6-4417-4c6e-b1f8-5e96f3d22643"
migrations_dir = "database/migrations"

[durable_objects]
bindings = [
  { name = "SUBSCRIPTION_POOL", class_name = "SubscriptionPool" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SubscriptionPool"]

## ============================================================================
## KV Namespaces
## ============================================================================

[[kv_namespaces]]
binding = "KV"                     # Access via env.KV
# id = "REPLACE_WITH_PROD_KV_ID"    # Set after running: wrangler kv namespace create safarnak-kv
# preview_id = "REPLACE_WITH_DEV_KV_ID"

## ============================================================================
## R2 Buckets
## ============================================================================

[[r2_buckets]]
binding = "R2"                     # Access via env.R2
bucket_name = "safarnak-dev"       # Create via: wrangler r2 bucket create safarnak-dev

## ============================================================================
## Vectorize Index (AI Embeddings)
## ============================================================================

[[vectorize]]
binding = "VECTORIZE"              # Access via env.VECTORIZE
index_name = "safarnak-embeddings" # Create via: wrangler vectorize index create safarnak-embeddings --dimension 768


