import { useMemo } from 'react';
import { View } from 'react-native';
import { useLocalSearchParams, Stack } from 'expo-router';
import { useTranslation } from 'react-i18next';
import * as Location from 'expo-location';
import MapView from '@components/MapView';
import { useGetTripQuery } from '@api';

export default function TripMapScreen() {
  const { t } = useTranslation();
  const { id } = useLocalSearchParams();
  const tripId = useMemo(() => (Array.isArray(id) ? id[0] : id) as string, [id]);

  // Fetch trip data to get coordinates and waypoints from GraphQL
  const { data, loading } = useGetTripQuery({
    variables: { id: tripId },
    skip: !tripId,
    fetchPolicy: 'cache-and-network',
    errorPolicy: 'all',
  });

  const trip = data?.getTrip as any;
  const location = trip?.coordinates ? ({ coords: trip.coordinates } as Location.LocationObject) : null;
  
  // Use waypoints from GraphQL (generated by server) - safely handle null/undefined/empty
  const waypoints = useMemo(() => {
    if (!trip?.waypoints || !Array.isArray(trip.waypoints) || trip.waypoints.length === 0) {
      return [];
    }
    // Filter out invalid waypoints and map to valid format
    return trip.waypoints
      .filter((wp: any) => wp && typeof wp.latitude === 'number' && typeof wp.longitude === 'number' && !isNaN(wp.latitude) && !isNaN(wp.longitude))
      .map((wp: any) => ({
        latitude: wp.latitude,
        longitude: wp.longitude,
        label: wp.label || undefined,
      }));
  }, [trip]);

  return (
    <View className="flex-1 bg-white dark:bg-black">
      <Stack.Screen
        options={{
          title: trip?.destination ? `${trip.destination} - ${t('map.map')}` : t('map.map'),
          headerShown: true,
        }}
      />
      <MapView location={location} waypoints={waypoints && waypoints.length > 0 ? waypoints : undefined} />
    </View>
  );
}
