import { gql } from '@apollo/client';
import {
  REGISTER_MUTATION as REGISTER_MUTATION_STRING,
  LOGIN_MUTATION as LOGIN_MUTATION_STRING,
  GET_MESSAGES_QUERY as GET_MESSAGES_QUERY_STRING,
  ADD_MESSAGE_MUTATION as ADD_MESSAGE_MUTATION_STRING,
  ME_QUERY as ME_QUERY_STRING,
} from '@graphql/queries';

// Wrap shared GraphQL strings with Apollo's gql tag
export const REGISTER_MUTATION = gql(REGISTER_MUTATION_STRING);
export const LOGIN_MUTATION = gql(LOGIN_MUTATION_STRING);
export const GET_MESSAGES_QUERY = gql(GET_MESSAGES_QUERY_STRING);
export const ADD_MESSAGE_MUTATION = gql(ADD_MESSAGE_MUTATION_STRING);
export const ME_QUERY = gql(ME_QUERY_STRING);
