name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  quick-check:
    name: Quick PR Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        working-directory: client
        run: yarn install --frozen-lockfile --prefer-offline

      - name: TypeScript check
        working-directory: client
        run: yarn tsc --noEmit

      - name: Format check
        working-directory: client
        run: yarn prettier --check . || echo "Format check skipped"
        continue-on-error: true

      - name: Comment on PR
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const status = '${{ job.status }}' === 'success' ? '✅' : '❌';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${status} Quick checks completed!\n\n**Status**: ${{ job.status }}`
            })

